from __future__ import annotations

SECTION_ALIASES = {
    "header": ["header"],
    "summary": [
        "summary",
        "profile",
        "professional summary",
        "about me",
        "objective",
        "career objective",
        "gioi thieu",
        "giới thiệu",
        "tom tat",
        "tóm tắt",
        "muc tieu nghe nghiep",
        "mục tiêu nghề nghiệp",
        "muc tieu",
        "mục tiêu",
        "about",
    ],
    "skills": [
        "skills",
        "technical skills",
        "core competencies",
        "tech stack",
        "stack",
        "ky nang",
        "kỹ năng",
        "cac ky nang",
        "các kỹ năng",
        "cong nghe",
        "công nghệ",
        "programming languages",
        "tools",
        "technical skills & tools",
    ],
    "experience": [
        "experience",
        "work experience",
        "employment history",
        "professional experience",
        "working experience",
        "kinh nghiem",
        "kinh nghiệm",
        "kinh nghiem lam viec",
        "kinh nghiệm làm việc",
        "qua trinh lam viec",
        "quá trình làm việc",
        "các công việc đã trải qua",
        "cac cong viec da trai qua",
        "work history",
    ],
    "education": [
        "education",
        "academic background",
        "hoc van",
        "học vấn",
        "trinh do hoc van",
        "trình độ học vấn",
        "hoc van va dao tao",
    ],
    "projects": [
        "projects",
        "personal projects",
        "selected projects",
        "du an",
        "dự án",
        "project",
        "du an tieu bieu",
        "dự án tiêu biểu",
        "school industrial project",
    ],
    "certifications": [
        "certifications",
        "certificates",
        "chung chi",
        "chứng chỉ",
        "courses",
        "khóa học",
        "khoa hoc",
    ],
    "activities": [
        "activities",
        "hoạt động",
        "hoat dong",
        "extracurricular activities",
        "hobbies",
        "sở thích",
        "so thich",
        "interests",
    ],
    "honours": [
        "honours",
        "honors",
        "awards",
        "achievements",
        "giải thưởng",
        "giai thuong",
        "điểm mạnh",
        "diem manh",
        "strengths",
    ],
    "languages": [
        "languages",
        "ngôn ngữ",
        "ngon ngu",
        "language",
        "english",
        "tiếng anh",
        "tieng anh",
    ],
}

SKILL_ALIASES = {
    "python": "python",
    "java": "java",
    "golang": "golang",
    "go": "golang",
    "javascript": "javascript",
    "typescript": "typescript",
    "c#": "c#",
    "c++": "c++",
    "sql": "sql",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "mysql": "mysql",
    "mongodb": "mongodb",
    "redis": "redis",
    "oracle": "oracle",
    "spark": "spark",
    "pyspark": "spark",
    "polars": "polars",
    "hadoop": "hadoop",
    "hive": "hive",
    "nifi": "nifi",
    "airflow": "airflow",
    "dbt": "dbt",
    "etl": "etl",
    "elt": "etl",
    "data warehouse": "data warehousing",
    "data warehousing": "data warehousing",
    "data mart": "data mart",
    "data lake": "data lake",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "redshift": "redshift",
    "aws": "aws",
    "amazon web services": "aws",
    "azure": "azure",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "terraform": "terraform",
    "linux": "linux",
    "git": "git",
    "github": "github",
    "gitlab": "gitlab",
    "jira": "jira",
    "fastapi": "fastapi",
    "flask": "flask",
    "django": "django",
    "spring": "spring",
    "spring boot": "spring boot",
    "nodejs": "nodejs",
    "node.js": "nodejs",
    "nestjs": "nestjs",
    "react": "react",
    "express": "express",
    "grails": "grails",
    "php": "php",
    "jquery": "jquery",
    "nextjs": "nextjs",
    "next.js": "nextjs",
    "vue": "vue",
    "pandas": "pandas",
    "numpy": "numpy",
    "matplotlib": "matplotlib",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "machine learning": "machine learning",
    "ml": "machine learning",
    "deep learning": "deep learning",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "opencv": "opencv",
    "xgboost": "xgboost",
    "lightgbm": "lightgbm",
    "mlflow": "mlflow",
    "power bi": "power bi",
    "tableau": "tableau",
    "excel": "excel",
    "llm": "llm",
    "large language model": "llm",
    "large language models": "llm",
    "rag": "rag",
    "retrieval augmented generation": "rag",
    "langchain": "langchain",
    "langgraph": "langgraph",
    "vector db": "vector database",
    "vector database": "vector database",
    "faiss": "faiss",
    "chroma": "chroma",
    "qdrant": "qdrant",
    "pinecone": "pinecone",
    "hugging face": "hugging face",
    "transformers": "transformers",
    "llamaindex": "llamaindex",
    "langsmith": "langsmith",
    "vllm": "vllm",
    "ollama": "ollama",
    "milvus": "milvus",
    "weaviate": "weaviate",
    "pydantic": "pydantic",
    "sqlalchemy": "sqlalchemy",
    "grpc": "grpc",
    "celery": "celery",
}

SKILL_FAMILIES = {
    "python": "programming",
    "java": "programming",
    "golang": "programming",
    "javascript": "programming",
    "typescript": "programming",
    "c#": "programming",
    "c++": "programming",
    "sql": "data",
    "postgresql": "database",
    "mysql": "database",
    "mongodb": "database",
    "redis": "database",
    "oracle": "database",
    "spark": "data",
    "polars": "data",
    "hadoop": "data",
    "hive": "data",
    "nifi": "data",
    "airflow": "data",
    "dbt": "data",
    "etl": "data",
    "data warehousing": "data",
    "data mart": "data",
    "data lake": "data",
    "snowflake": "data",
    "bigquery": "data",
    "redshift": "data",
    "aws": "cloud",
    "azure": "cloud",
    "docker": "devops",
    "kubernetes": "devops",
    "terraform": "devops",
    "linux": "devops",
    "git": "engineering",
    "github": "engineering",
    "gitlab": "engineering",
    "jira": "engineering",
    "fastapi": "backend",
    "flask": "backend",
    "django": "backend",
    "spring": "backend",
    "spring boot": "backend",
    "nodejs": "backend",
    "nestjs": "backend",
    "express": "backend",
    "grails": "backend",
    "php": "backend",
    "jquery": "frontend",
    "react": "frontend",
    "nextjs": "frontend",
    "vue": "frontend",
    "pandas": "data",
    "numpy": "data",
    "matplotlib": "data",
    "scikit-learn": "ml",
    "machine learning": "ml",
    "deep learning": "ml",
    "tensorflow": "ml",
    "pytorch": "ml",
    "opencv": "ml",
    "xgboost": "ml",
    "lightgbm": "ml",
    "mlflow": "ml",
    "power bi": "bi",
    "tableau": "bi",
    "excel": "bi",
    "llm": "ai",
    "rag": "ai",
    "langchain": "ai",
    "langgraph": "ai",
    "vector database": "database",
    "faiss": "database",
    "chroma": "database",
    "qdrant": "database",
    "pinecone": "database",
    "hugging face": "ai",
    "transformers": "ai",
    "llamaindex": "ai",
    "langsmith": "ai",
    "vllm": "ai",
    "ollama": "ai",
    "milvus": "database",
    "weaviate": "database",
    "pydantic": "backend",
    "sqlalchemy": "backend",
    "grpc": "backend",
    "celery": "backend",
}

ROLE_ALIASES = {
    "ai engineer": [
        "ai engineer",
        "llm engineer",
        "genai engineer",
        "rag engineer",
        "ai intern",
        "thực tập sinh ai",
        "data scientist & ai engineer",
        "ai engineer / data scientist",
    ],
    "ml engineer": ["ml engineer", "machine learning engineer", "mle", "machine learning intern"],
    "data scientist": ["data scientist", "research scientist", "chuyên viên khoa học dữ liệu", "khoa học dữ liệu"],
    "data engineer": [
        "data engineer",
        "big data engineer",
        "etl developer",
        "etl engineer",
        "data platform engineer",
        "analytics engineer",
        "kỹ sư dữ liệu",
        "chuyên viên phòng khoa học dữ liệu",
    ],
    "data analyst": [
        "data analyst",
        "business analyst",
        "bi analyst",
        "analytics analyst",
        "fresher data analyst",
        "chuyên viên phân tích dữ liệu",
        "phân tích dữ liệu",
    ],
    "backend engineer": ["backend engineer", "backend developer", "software engineer", "software developer", "api developer"],
    "frontend engineer": ["frontend engineer", "frontend developer", "ui engineer", "web developer"],
    "fullstack engineer": ["fullstack engineer", "full-stack engineer", "fullstack developer", "full-stack developer"],
    "devops engineer": ["devops engineer", "site reliability engineer", "sre", "platform engineer", "software/devops engineer"],
    "mobile engineer": ["android developer", "ios developer", "mobile developer", "mobile engineer", "flutter developer"],
    "hr recruiter": ["recruiter", "talent acquisition", "hr executive", "technical recruiter"],
}

DEGREE_ALIASES = {
    "bachelor": ["bachelor", "cử nhân", "cu nhan", "undergraduate", "bachelor of engineering", "bachelor of science"],
    "master": ["master", "thạc sĩ", "thac si", "master of science"],
    "phd": ["phd", "doctor of philosophy", "tiến sĩ", "tien si"],
}

ACADEMIC_KEYWORDS = {
    "computer science": ["computer science", "khoa học máy tính", "khoa hoc may tinh"],
    "software engineering": ["software engineering", "công nghệ phần mềm", "cong nghe phan mem"],
    "information technology": ["information technology", "công nghệ thông tin", "cong nghe thong tin", "hệ thống thông tin", "he thong thong tin"],
    "artificial intelligence": ["artificial intelligence", "trí tuệ nhân tạo", "tri tue nhan tao", "machine learning & neural networks"],
    "data science": ["data science", "khoa học dữ liệu", "khoa hoc du lieu", "data analytics", "data science in economy and business"],
    "applied mathematics": ["toán ứng dụng", "toan ung dung"],
}

LOCATION_ALIASES = {
    "ha noi": ["hà nội", "ha noi", "hn", "thanh xuân", "thanh xuan", "đống đa", "dong da", "long biên", "long bien", "định công", "dinh cong"],
    "ho chi minh": ["hồ chí minh", "ho chi minh", "hcm", "tp hcm", "sài gòn", "sai gon"],
    "da nang": ["đà nẵng", "da nang"],
    "hai duong": ["hải dương", "hai duong"],
    "finland": ["finland"],
    "belgium": ["belgium"],
    "remote": ["remote"],
}

JOB_TITLE_TOKENS = {
    token
    for canonical, aliases in ROLE_ALIASES.items()
    for phrase in [canonical, *aliases]
    for token in phrase.split()
}

GENERIC_FILENAME_TOKENS = {
    "cv",
    "resume",
    "profile",
    "candidate",
    "ung",
    "vien",
    "topcv",
    "pdf",
    "data",
    "engineer",
    "scientist",
    "analyst",
    "ai",
    "ml",
    "de",
    "da",
    "ds",
}