from __future__ import annotations

SECTION_ALIASES = {
    "header": ["header"],
    "summary": [
        "summary", "profile", "professional summary", "about me",
        "objective", "career objective", "gioi thieu", "giới thiệu",
        "tom tat", "tóm tắt", "muc tieu nghe nghiep", "mục tiêu nghề nghiệp",
    ],
    "skills": [
        "skills", "technical skills", "core competencies",
        "ky nang", "kỹ năng", "cong nghe", "công nghệ",
    ],
    "experience": [
        "experience", "work experience", "employment history",
        "professional experience", "kinh nghiem", "kinh nghiệm",
        "qua trinh lam viec", "quá trình làm việc",
    ],
    "education": [
        "education", "academic background",
        "hoc van", "học vấn", "trinh do hoc van", "trình độ học vấn",
    ],
    "projects": [
        "projects", "personal projects", "selected projects",
        "du an", "dự án",
    ],
    "certifications": [
        "certifications", "certificates", "chung chi", "chứng chỉ",
    ],
}

SKILL_ALIASES = {
    "python": "python",
    "java": "java",
    "sql": "sql",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "mysql": "mysql",
    "mongodb": "mongodb",
    "redis": "redis",
    "spark": "spark",
    "pyspark": "spark",
    "hadoop": "hadoop",
    "airflow": "airflow",
    "dbt": "dbt",
    "etl": "etl",
    "elt": "elt",
    "data warehouse": "data warehousing",
    "data warehousing": "data warehousing",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "redshift": "redshift",
    "aws": "aws",
    "amazon web services": "aws",
    "s3": "aws",
    "ec2": "aws",
    "lambda": "aws",
    "glue": "aws",
    "athena": "aws",
    "emr": "aws",
    "gcp": "gcp",
    "google cloud": "gcp",
    "azure": "azure",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "terraform": "terraform",
    "linux": "linux",
    "git": "git",
    "github": "github",
    "fastapi": "fastapi",
    "flask": "flask",
    "django": "django",
    "pandas": "pandas",
    "numpy": "numpy",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "machine learning": "machine learning",
    "deep learning": "deep learning",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "power bi": "power bi",
    "tableau": "tableau",
    "excel": "excel",
}

SKILL_FAMILIES = {
    "python": "programming",
    "java": "programming",
    "sql": "data",
    "postgresql": "database",
    "mysql": "database",
    "mongodb": "database",
    "redis": "database",
    "spark": "data",
    "hadoop": "data",
    "airflow": "data",
    "dbt": "data",
    "etl": "data",
    "data warehousing": "data",
    "snowflake": "data",
    "bigquery": "data",
    "redshift": "data",
    "aws": "cloud",
    "gcp": "cloud",
    "azure": "cloud",
    "docker": "devops",
    "kubernetes": "devops",
    "terraform": "devops",
    "linux": "devops",
    "git": "engineering",
    "github": "engineering",
    "fastapi": "backend",
    "flask": "backend",
    "django": "backend",
    "pandas": "data",
    "numpy": "data",
    "scikit-learn": "ml",
    "machine learning": "ml",
    "deep learning": "ml",
    "tensorflow": "ml",
    "pytorch": "ml",
    "power bi": "bi",
    "tableau": "bi",
    "excel": "bi",
}

ROLE_ALIASES = {
    "data engineer": [
        "data engineer", "big data engineer", "etl developer",
        "etl engineer", "data platform engineer", "analytics engineer",
    ],
    "data analyst": [
        "data analyst", "business analyst", "bi analyst",
        "analytics analyst",
    ],
    "data scientist": [
        "data scientist", "ml engineer", "machine learning engineer",
        "ai engineer",
    ],
    "backend engineer": [
        "backend engineer", "backend developer", "software engineer",
        "software developer", "api developer",
    ],
    "devops engineer": [
        "devops engineer", "site reliability engineer", "sre",
        "platform engineer",
    ],
}

DEGREE_ALIASES = {
    "bachelor": ["bachelor", "cử nhân", "cu nhan", "engineer", "kỹ sư", "ky su"],
    "master": ["master", "thạc sĩ", "thac si"],
    "phd": ["phd", "doctor", "tiến sĩ", "tien si"],
}

LOCATION_ALIASES = {
    "ha noi": ["hà nội", "ha noi", "hn"],
    "ho chi minh": ["hồ chí minh", "ho chi minh", "hcm", "tp hcm", "sài gòn", "sai gon"],
    "da nang": ["đà nẵng", "da nang"],
    "remote": ["remote", "work from home", "wfh", "hybrid"],
}